In [2]:
import torch
print(torch.__version__)

2.10.0+cu128


In [3]:
if torch.cuda.is_available():
  print("GPU is available!")
  print(f("Using GPU: {torch.cuda.get_device_name(0)}"))
else:
  print("GPU not available. Using CPU.")

GPU not available. Using CPU.


##Creating a Tensor

In [4]:
# using empty
a = torch.empty(2,3) #showing existing value in memory block
print(a)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.6567e+26, 4.5085e-41]])


In [5]:
# check type
type(a)

torch.Tensor

In [6]:
# using zeros
b = torch.zeros(2, 3)
print(b)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [7]:
# using ones
c = torch.ones(2, 3)
print(c)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [8]:
# using rand
d = torch.rand(2, 3) #initializes random value between 0 and 1
print(d)

tensor([[0.0236, 0.0123, 0.5319],
        [0.6340, 0.8228, 0.6135]])


In [9]:
# use of seed
torch.manual_seed(100) #fix the random values for reproducability
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
torch.manual_seed(100)
torch.rand(2,3) #should be same as previous

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
# using tensor
torch.tensor([[1, 2, 3],[4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
# other ways

# arange
print("using arange -> ", torch.arange(0,10, 2)) #give range and step

# using linspace
print("using linspace -> ", torch.linspace(0,10,10)) #create 10 evenly spaced values between 0 and 10

# using eye
print("using eye -> ", torch.eye(5)) # 5x5 identity matrix

# using full
print("using full -> ", torch.full((3, 3), 5)) #create a 3x3 matrix each of value 5

using arange ->  tensor([0, 2, 4, 6, 8])
using linspace ->  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye ->  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full ->  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor shape

In [13]:
x = torch.tensor([[1, 2, 3],[4, 5, 6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
x.shape

torch.Size([2, 3])

In [15]:
# create a tensor of shape of some other tensor
torch.empty_like(x)

tensor([[138188106362304, 138188106362304,       297952704],
        [138187524109616,       297952704,           65280]])

In [16]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [17]:
torch.rand_like(x) # will not work as x is of int data type but rand generates value between 0 and 1 i.e. floating type.

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

In [18]:
# solution of above issue
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Tensor Data Types

In [19]:
# find data type
x.dtype

torch.int64

In [20]:
# assign data type
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [21]:
torch.tensor([1, 2, 3], dtype=torch.float32)

tensor([1., 2., 3.])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical Operations
### 1. Scalar operations


In [22]:
x = torch.rand(2, 2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [23]:
# addition
x + 2

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])

In [24]:
# substraction
x - 2

tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])

In [25]:
# multiplication
x * 3

tensor([[2.1353, 2.3627],
        [1.2549, 2.7042]])

In [26]:
# division
x / 3

tensor([[0.2373, 0.2625],
        [0.1394, 0.3005]])

In [27]:
# int division
(x * 100)//3

tensor([[23., 26.],
        [13., 30.]])

In [28]:
# mod
((x * 100)//3)%2

tensor([[1., 0.],
        [1., 0.]])

In [29]:
# power
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

### 2. Element Wise Operation

In [30]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)
print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [31]:
# add
a + b

tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])

In [32]:
# sub
a - b

tensor([[ 0.4411, -0.2205, -0.2201],
        [-0.6455, -0.5661,  0.3346]])

In [33]:
# multiply
a * b

tensor([[0.5540, 0.7391, 0.0994],
        [0.2866, 0.1328, 0.4030]])

In [34]:
# division
a / b

tensor([[1.7938, 0.7743, 0.5042],
        [0.3190, 0.2397, 1.6841]])

In [35]:
# power
a ** b

tensor([[0.9983, 0.7614, 0.5145],
        [0.3218, 0.2771, 0.9096]])

In [36]:
# mod
a % b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [37]:
c = torch.tensor([1, -2, 3, -4])

In [38]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [39]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [40]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [45]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [46]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [47]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [48]:
# clamp ( squeeze to a certain range )
torch.clamp(d, min = 2, max = 3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction Operation
Reduce the entire tensor to a number.


In [59]:
e = torch.randint(size = (2, 3), low = 0, high = 10, dtype = torch.float32)
e

tensor([[5., 7., 5.],
        [9., 9., 7.]])

In [60]:
# sum
torch.sum(e)

tensor(42.)

In [61]:
# sum along columns
torch.sum(e, dim = 0)

tensor([14., 16., 12.])

In [62]:
# sum along row
torch.sum(e, dim = 1)

tensor([17., 25.])

In [63]:
# mean
torch.mean(e)

tensor(7.)

In [64]:
# mean along column
torch.mean(e, dim = 0)

tensor([7., 8., 6.])

In [65]:
# mean along rows
torch.mean(e, dim = 1)

tensor([5.6667, 8.3333])

In [66]:
# median
torch.median(e)

tensor(7.)

In [67]:
# max
torch.max(e)

tensor(9.)

In [68]:
# min
torch.min(e)

tensor(5.)

In [69]:
# product
torch.prod(e)

tensor(99225.)

In [70]:
# standard deviation
torch.std(e)

tensor(1.7889)

In [71]:
# variance
torch.var(e)

tensor(3.2000)

In [72]:
# argmax (position of max element)
torch.argmax(e)

tensor(3)

In [73]:
# argmin (position of minimum element)
torch.argmin(e)

tensor(0)

### 4. Matrix Operations

In [75]:
f = torch.randint(size = (2, 3), low = 0, high = 10)
g = torch.randint(size = (3, 2), low = 0, high = 10)
print(f)
print(g)

tensor([[5, 9, 8],
        [9, 7, 9]])
tensor([[2, 6],
        [7, 7],
        [8, 3]])


In [76]:
# matrix multiplication
torch.matmul(f, g)

tensor([[137, 117],
        [139, 130]])

In [77]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

In [78]:
# dot product
torch.dot(vector1, vector2)

tensor(11)

In [79]:
print(f)

tensor([[5, 9, 8],
        [9, 7, 9]])


In [83]:
# transpose
torch.transpose(f, 0, 1)

tensor([[5, 9],
        [9, 7],
        [8, 9]])

In [92]:
h = torch.randint(size = (3, 3), low = 0, high = 10, dtype = torch.float32)
h

tensor([[4., 5., 6.],
        [9., 2., 3.],
        [1., 0., 2.]])

In [93]:
# determinant
torch.det(h)

tensor(-71.0000)

In [94]:
# inverse
torch.inverse(h)

tensor([[-0.0563,  0.1408, -0.0423],
        [ 0.2113, -0.0282, -0.5915],
        [ 0.0282, -0.0704,  0.5211]])

### 5. Comparison Operations

In [96]:
i = torch.randint(size=(2, 3), low = 0, high = 10)
j = torch.randint(size=(2, 3), low = 0, high = 10)

print(i)
print(j)

tensor([[1, 2, 7],
        [9, 2, 4]])
tensor([[6, 6, 8],
        [4, 9, 0]])


In [97]:
# greater than
i > j

tensor([[False, False, False],
        [ True, False,  True]])

In [98]:
# less than
i < j

tensor([[ True,  True,  True],
        [False,  True, False]])

In [101]:
# equals to
i == j

tensor([[False, False, False],
        [False, False, False]])

In [100]:
# not equals to
i != j

tensor([[True, True, True],
        [True, True, True]])

In [103]:
# greater than equal to
# less than equal to

### 6. Special functions

In [117]:
k = torch.randint(size=(2, 3), low = 0, high = 10, dtype=torch.float32)
k

tensor([[4., 4., 6.],
        [2., 1., 0.]])

In [118]:
# log
torch.log(k)

tensor([[1.3863, 1.3863, 1.7918],
        [0.6931, 0.0000,   -inf]])

In [119]:
# exp
torch.exp(k)

tensor([[ 54.5981,  54.5981, 403.4288],
        [  7.3891,   2.7183,   1.0000]])

In [120]:
# sqrt
torch.sqrt(k)

tensor([[2.0000, 2.0000, 2.4495],
        [1.4142, 1.0000, 0.0000]])

In [121]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9820, 0.9820, 0.9975],
        [0.8808, 0.7311, 0.5000]])

In [123]:
# softmax
torch.softmax(k, dim = 0)

tensor([[0.8808, 0.9526, 0.9975],
        [0.1192, 0.0474, 0.0025]])

In [124]:
# relu
torch.relu(k)

tensor([[4., 4., 6.],
        [2., 1., 0.]])

## Inplace Operations

In [3]:
n = torch.rand(2, 3)
m = torch.rand(2, 3)

print(n)
print(m)

tensor([[0.1366, 0.5880, 0.1409],
        [0.5318, 0.0950, 0.8601]])
tensor([[0.7856, 0.3098, 0.5903],
        [0.9161, 0.1133, 0.7928]])


In [4]:
# add_() allows inplace addition inorder to save memory as m+n will at new memory location
m.add_(n)

tensor([[0.9222, 0.8978, 0.7311],
        [1.4480, 0.2083, 1.6529]])

In [5]:
n

tensor([[0.1366, 0.5880, 0.1409],
        [0.5318, 0.0950, 0.8601]])

In [6]:
m

tensor([[0.9222, 0.8978, 0.7311],
        [1.4480, 0.2083, 1.6529]])

In [7]:
# applying inplace relu function
m.relu_()

tensor([[0.9222, 0.8978, 0.7311],
        [1.4480, 0.2083, 1.6529]])

In [8]:
# Note:- (_) underscore infront a function make the operation inplace.

## Copying a Tensor

In [9]:
a = torch.rand(2, 3)
a

tensor([[0.2264, 0.5370, 0.1283],
        [0.2954, 0.1292, 0.4072]])

In [10]:
# assignment operator
b = a

In [11]:
b

tensor([[0.2264, 0.5370, 0.1283],
        [0.2954, 0.1292, 0.4072]])

In [14]:
# copying makes new variable point to the rhs variable (no new memory for data is created.)
# changes to any one variable will be reflected to the other
print(id(a))
print(id(b))

133134188489424
133134188489424


In [15]:
# If yoy want to assign value to a new memory location
c = a.clone()

In [16]:
print(id(a))
print(id(c))

133134188489424
133134188648544


In [18]:
a[0][0] = 10
print(a)
print(c)

tensor([[10.0000,  0.5370,  0.1283],
        [ 0.2954,  0.1292,  0.4072]])
tensor([[0.2264, 0.5370, 0.1283],
        [0.2954, 0.1292, 0.4072]])


## Tensor Operations on GPU

In [3]:
# If you are using google colab then change runtime to GPU
torch.cuda.is_available()

True

In [4]:
device = torch.device("cuda") # creating a variable to store gpu preference

In [5]:
# creating a new tensor or gpu
torch.rand((2,3), device=device)

tensor([[0.1815, 0.8920, 0.1303],
        [0.0362, 0.8240, 0.9809]], device='cuda:0')

In [6]:
# moving existing tensor to gpu
a = torch.rand(2,3)
a # currently on cpu

tensor([[0.1087, 0.1554, 0.9090],
        [0.9466, 0.7650, 0.8983]])

In [7]:
b = a.to(device)

In [9]:
# check in which processing device the veriables are stored
print("a is stored in \"", a.device, "\"")
print("b is stored in \"", b.device, "\"")

a is stored in " cpu "
b is stored in " cuda:0 "


## Speed Comparison CPU vs GPU

In [5]:
import time

# Derine the size of the matrices
size = 10000 # Large size for performance comparison

# Create random matrices on CPU
matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

# Measure time on CPU1
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)

# Matrix multiplication on CPU
cpu_time = time.time() - start_time
print(f"Time on CPU: {cpu_time: .4f} seconds")

# Move matrices to GrU.
matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

# Measure time on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2) # Matrix multiplication on GPU
torch.cuda.synchronize() # Ensure all GPU operations are completel
gpu_time = time.time() - start_time

print(f"Time on GPU: {gpu_time:.4f} seconds")

# compare results
print("\nSpeedup (CPU time / GPU time): ", cpu_time/gpu_time)

Time on CPU:  16.1339 seconds
Time on GPU: 0.5730 seconds

Speedup (CPU time / GPU time):  28.156501951640266


## Reshaping Tensors

In [6]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [7]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [8]:
# flatten
a.flatten() # 1D tensor

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
b = torch.rand(2, 3, 4)
b

tensor([[[0.8970, 0.6981, 0.8519, 0.4967],
         [0.4139, 0.0614, 0.1260, 0.8357],
         [0.8712, 0.0786, 0.9949, 0.9915]],

        [[0.3217, 0.2718, 0.3035, 0.2351],
         [0.3919, 0.1475, 0.3633, 0.8339],
         [0.1700, 0.3546, 0.5729, 0.5516]]])

In [20]:
# permute
b.permute(2, 1, 0).shape

torch.Size([4, 3, 2])

In [21]:
b.permute(2, 0, 1).shape

torch.Size([4, 2, 3])

In [22]:
c = b.permute(2,0,1)

In [23]:
c

tensor([[[0.8970, 0.4139, 0.8712],
         [0.3217, 0.3919, 0.1700]],

        [[0.6981, 0.0614, 0.0786],
         [0.2718, 0.1475, 0.3546]],

        [[0.8519, 0.1260, 0.9949],
         [0.3035, 0.3633, 0.5729]],

        [[0.4967, 0.8357, 0.9915],
         [0.2351, 0.8339, 0.5516]]])

In [26]:
# unsqueeze
d = torch.rand(226, 226, 3) # typical image
d.unsqueeze(0).shape # 0,1,2... means where do you need to add a new dimension

torch.Size([1, 226, 226, 3])

In [27]:
d.unsqueeze(1).shape

torch.Size([226, 1, 226, 3])

In [28]:
# squeeze
e = torch.rand(1, 20)
e.squeeze(0).shape

torch.Size([20])

## Numpy and Pytorch
How to move tensors between numpy and pytorch.

In [30]:
import numpy as np

In [38]:
# pytorch tensor from numpy

In [32]:
a = torch.tensor([1, 2, 3])
a

tensor([1, 2, 3])

In [35]:
b = a.numpy()
b

array([1, 2, 3])

In [36]:
type(b)

numpy.ndarray

In [37]:
c = np.array([1, 2, 3])
c

array([1, 2, 3])

In [39]:
torch.from_numpy(c)

tensor([1, 2, 3])