## Agenda :
- Undestand use of <mark>torch.nn</mark> module and <mark>torch.optim</mark> module.
- Building the Neural Network using <mark>nn</mark> module.
- Using Built-in activation function.
- Using Built-in loss function.
- Using Built-in optimizer.


# 📚 The `nn` Module

The `torch.nn` module in PyTorch is a core library that provides a wide array of classes and functions designed to help developers build neural networks efficiently and effectively. It abstracts the complexity of creating and training neural networks by offering pre-built layers, loss functions, activation functions, and other utilities, enabling you to focus on designing and experimenting with model architectures.

---

## 🔑 Key Components of `torch.nn`

### 1. 🏗️ Modules (Layers)
* **`nn.Module`**: The base class for all neural network modules. Your custom models and layers must subclass this class.
* **Common Layers**: Includes pre-built structural blocks like:
  * `nn.Linear` *(fully connected layer)*
  * `nn.Conv2d` *(convolutional layer)*
  * `nn.LSTM` *(recurrent layer)*

### 2. ⚡ Activation Functions
* **Purpose**: Introduces non-linearities to the network model, allowing it to learn highly complex patterns.
* **Examples**: `nn.ReLU`, `nn.Sigmoid`, and `nn.Tanh`.

### 3. 📉 Loss Functions
* **Purpose**: Quantifies the numerical difference between the model's predictions and the actual targets.
* **Examples**: `nn.CrossEntropyLoss`, `nn.MSELoss`, and `nn.NLLLoss`.

### 4. 📦 Container Modules
* **`nn.Sequential`**: A linear sequential container used to cleanly stack operational layers in a fixed chronological order.

### 5. 🛡️ Regularization and Dropout
* **Purpose**: Prevents overfitting and improves the model's structural ability to generalize well to brand new data.
* **Examples**: `nn.Dropout` and `nn.BatchNorm2d`.





# ⚙️ The `torch.optim` Module

`torch.optim` is a module in PyTorch that provides a variety of optimization algorithms used to update the parameters of your model during training.

---

## 🛠️ Key Capabilities

* **Common Optimizers**: Includes standard pre-built algorithms like:
  * `Stochastic Gradient Descent (SGD)`
  * `Adam`
  * `RMSprop`
* **Efficiency**: Handles weight updates efficiently across all layers automatically.
* **Advanced Features**: Includes built-in support for **learning rate scheduling** and **weight decay** (regularization).

---

## 🧠 Parameter Retrieval: `model.parameters()`

The `model.parameters()` method in PyTorch retrieves an iterator over all the trainable parameters in a model. These parameters are instances of `torch.nn.Parameter` and include:

* **Weights**: The weight matrices of structural layers like `nn.Linear`, `nn.Conv2d`, etc.
* **Biases**: The baseline offset terms of the layers (if they exist).

> 🔄 **Usage:** The optimizer uses these retrieved parameters to compute gradients and update them during training.


In [1]:
import torch
import torch.nn as nn

In [2]:
# create model class
class Model(nn.Module): # Model class is inheriting nn.Module class

  def __init__(self, num_features):
    super().__init__() # invoking parent class constructor
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

In [3]:
# create a dataset
features = torch.rand(10, 5)

# create model
model = Model(features.shape[1])

# call model for forward pass
#model.forward(features)
model(features) # forward method gets triggered and we will get y_pred

tensor([[0.5537],
        [0.5247],
        [0.4616],
        [0.4469],
        [0.4986],
        [0.4658],
        [0.5984],
        [0.4748],
        [0.4799],
        [0.4765]], grad_fn=<SigmoidBackward0>)

In [4]:
# show model weights
model.linear.weight

Parameter containing:
tensor([[ 0.2932, -0.2397,  0.3843,  0.1950, -0.4190]], requires_grad=True)

In [5]:
# show model bias
model.linear.bias

Parameter containing:
tensor([-0.0875], requires_grad=True)

In [6]:
# Need to visualize the entire network
!pip install torchinfo

In [7]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## Lets Create a little more Complex Network
- Input layer with $5$ input features.
- Hidden Layer with $3$ neurons.
- Output layer with $1$ neuron.
- Relu activation $F^n$ in Hidden Layer and $Sigmoid$ activation in output layer.

In [8]:
# create model class
class Model2(nn.Module): # Model class is inheriting nn.Module class

  def __init__(self, num_features):
    super().__init__() # invoking parent class constructor
    self.linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)
    return out

In [9]:
# create model2 object
model2 = Model2(features.shape[1])

# call model2 for forward pass
model2(features)

tensor([[0.3644],
        [0.2950],
        [0.3406],
        [0.3340],
        [0.3294],
        [0.3600],
        [0.3549],
        [0.3086],
        [0.3327],
        [0.3053]], grad_fn=<SigmoidBackward0>)

In [10]:
model2.linear1.weight

Parameter containing:
tensor([[ 0.4153,  0.1236,  0.4382,  0.1807,  0.3278],
        [ 0.3802,  0.2871,  0.1678, -0.4208, -0.2316],
        [ 0.4076, -0.1643,  0.1420, -0.2862,  0.2140]], requires_grad=True)

In [11]:
model2.linear2.weight

Parameter containing:
tensor([[ 0.2503, -0.1037, -0.5766]], requires_grad=True)

In [12]:
model2.linear1.bias

Parameter containing:
tensor([-0.2619, -0.1024,  0.4043], requires_grad=True)

In [13]:
model2.linear2.bias

Parameter containing:
tensor([-0.4697], requires_grad=True)

In [14]:
summary(model2, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model2                                   [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## The forward pass method look very cumbursome. Can we simplify it?

```python
 def forward(self, features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)
    return out
```

**Yes we can. By using Sequential Containers**

In [15]:
class Model3(nn.Module): # Model class is inheriting nn.Module class

  def __init__(self, num_features):
    super().__init__() # invoking parent class constructor
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):
    out = self.network(features)
    return out

In [16]:
# create model3 object
model3 = Model3(features.shape[1])

# call model3 for forward pass
model3(features)

tensor([[0.4311],
        [0.4452],
        [0.4204],
        [0.4743],
        [0.4723],
        [0.4187],
        [0.4067],
        [0.4473],
        [0.4818],
        [0.4508]], grad_fn=<SigmoidBackward0>)

## Applying `NN module` for Breast cancer Classifier in `3. Pytorch_Training_Pipeline_(One_Neuron_Network).ipynb`

```python
# -*- coding: utf-8 -*-
"""3. Pytorch_Training_Pipeline_(One_Neuron_Network).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j-buEYZxNkz5meA5E2fLX16UEUwB-cQh

## Plan of Action
1. <i>We will build a simple neural network
2. Train it on a real world dataset
3. Will mimic the PyTorch workflow</i>

### Codeflow
1. <i>Load the dataset
2. Basic preprocessing
3. Training Process
  - 1. Create the model
  - 2. Forward pass
  - 3. Loss calculation
  - 4. Backprop
  - 5. Parameters update
4. Model evaluation</i>
"""

import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()

df.shape

df.drop(columns=["id", "Unnamed: 32"], inplace = True)

df.head()

"""### Train Test Split"""

X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

"""### Scaling"""

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

X_train

y_train

# Need to encode labels
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

y_train

"""### Numpy arrays to Pytorch Tensors"""

X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

X_train_tensor

X_train_tensor.shape

y_train_tensor.shape

"""### Defining the model"""

class MySimpleNN():
  def __init__(self, X):
    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True) # 30x1 matrix
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True) # onlu 1 neuron so 1 bias

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias # z = w*x + b
    y_pred = torch.sigmoid(z) # activation function (sigmoid)
    return y_pred

  def loss_function(self, y_pred, y):
    # clamp prediction to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)
    # calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

"""### Important Parameters

"""

learning_rate = 0.1
epochs = 25

"""### Training Pipeline"""

# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):
  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculation
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
    # since we dont need gradient tracking during parameter update use below line otherwise will throw error
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # disable gradient tracking i.e. reset the gradients or avoid gradient accumulation (zero gradients)
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print the loss in each epoch
  print(f"Epoch: {epoch + 1}, loss: {loss.item()}")

#print(model.weights)
print(model.bias)

"""### Model Evaluation"""

# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor) # sigmoid value between 0 and 1
  y_pred = (y_pred > 0.5).float() # value of y_pred > 0.5 is 1
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f"Accuracy: {accuracy.item()}")
```

- Adding Built-In Loss Function.

- Adding Built-In Optimizer

In [17]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")

df.drop(columns=["id", "Unnamed: 32"], inplace = True)

"""### Train Test Split"""

X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

"""### Scaling"""

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Need to encode labels
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

"""### Numpy arrays to Pytorch Tensors"""

X_train_tensor = torch.from_numpy(X_train).float()
X_test_tensor = torch.from_numpy(X_test).float()
y_train_tensor = torch.from_numpy(y_train).float()
y_test_tensor = torch.from_numpy(y_test).float()

"""### Defining the model"""

class MySimpleNN(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

  # removed custom loss function from here


In [18]:
"""Important Parameters"""

learning_rate = 0.1
epochs = 25

""" Adding Built-In Loss Function """
loss_function = nn.BCELoss()


In [19]:
"""### Training Pipeline"""

# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate) # The model.parameters() method in PyTorch retrieves an iterator over all the trainable parameters (weights and biases) in a model

# define loop
for epoch in range(epochs):
  # forward pass
  y_pred = model(X_train_tensor)

  # loss calculation
  loss = loss_function(y_pred, y_train_tensor.view(-1, 1))

  # its a good practice to reset gradients before backward pass
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # parameter update
  optimizer.step()

  # disable gradient tracking i.e. reset the gradients or avoid gradient accumulation (zero gradients)
  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()

  # print the loss in each epoch
  print(f"Epoch: {epoch + 1}, loss: {loss.item()}")

Epoch: 1, loss: 0.7169961333274841
Epoch: 2, loss: 0.5325711369514465
Epoch: 3, loss: 0.4369213879108429
Epoch: 4, loss: 0.3787165582180023
Epoch: 5, loss: 0.33919358253479004
Epoch: 6, loss: 0.310348242521286
Epoch: 7, loss: 0.28820353746414185
Epoch: 8, loss: 0.2705562114715576
Epoch: 9, loss: 0.2560844421386719
Epoch: 10, loss: 0.24394582211971283
Epoch: 11, loss: 0.23357686400413513
Epoch: 12, loss: 0.22458603978157043
Epoch: 13, loss: 0.21669210493564606
Epoch: 14, loss: 0.20968769490718842
Epoch: 15, loss: 0.20341624319553375
Epoch: 16, loss: 0.19775719940662384
Epoch: 17, loss: 0.19261600077152252
Epoch: 18, loss: 0.18791751563549042
Epoch: 19, loss: 0.1836010068655014
Epoch: 20, loss: 0.17961691319942474
Epoch: 21, loss: 0.17592424154281616
Epoch: 22, loss: 0.17248892784118652
Epoch: 23, loss: 0.16928218305110931
Epoch: 24, loss: 0.166279599070549
Epoch: 25, loss: 0.1634603589773178


In [20]:
 # model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor) # sigmoid value between 0 and 1
  y_pred = (y_pred > 0.5).float() # value of y_pred > 0.5 is 1
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.5323176383972168
