In [34]:
import pickle
import numpy as np

In [35]:
ohe_sex = pickle.load(open('models/ohe_sex.pkl', 'rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl', 'rb'))
clf = pickle.load(open('models/clf.pkl', 'rb'))

In [36]:
# Assume User Imput
# Pclass/gender/age/SibSp/Parch/Fare/Embarked
test_input = np.array([2, 'male', 3.0, 0, 0, 0.5, 'S'], dtype = object).reshape(1, 7)

In [37]:
test_input

array([[2, 'male', 3.0, 0, 0, 0.5, 'S']], dtype=object)

In [38]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1, 1))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [39]:
test_input_sex

array([[0, 1]], dtype=int32)

In [40]:
test_input_embarked = ohe_embarked.transform(test_input[:, -1].reshape(1, 1))

In [41]:
test_input_embarked

array([[0, 0, 1]], dtype=int32)

In [42]:
test_input_age = test_input[:, 2].reshape(1, 1)

In [43]:
# order of features for concatenation should be same as done for training
test_input_transformed = np.concatenate((test_input[:, [0, 3, 4, 5]], test_input_age, test_input_sex, test_input_embarked), axis = 1)

In [44]:
test_input_transformed.shape

(1, 10)

In [45]:
clf.predict(test_input_transformed)

array([1])